[project]
name = "tsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.6",
    "matplotlib>=3.10.1",
    "numba>=0.61.0",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
